#IMPORTING/EXPORTING

In [3]:
import numpy as np

In [4]:
data = np.loadtxt('file.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
data = np.genfromtxt('file.csv', delimiter=',')
print(data)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt('file.txt', arr, delimiter=' ')
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.savetxt('file.csv', arr, delimiter=',')

#CREATING ARRAYS

In [8]:
a = np.array([1,2,3])
print(a)


[1 2 3]


In [9]:
b = np.array([(1,2,3),(4,5,6)])
print(b)


[[1 2 3]
 [4 5 6]]


In [10]:
c = np.zeros(3)
print(c)


[0. 0. 0.]


In [11]:
d = np.ones((3,4))
print(d)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
e = np.eye(5)
print(e)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
f = np.linspace(0,100,6)
print(f)


[  0.  20.  40.  60.  80. 100.]


In [14]:
g = np.arange(0,10,3)
print(g)


[0 3 6 9]


In [15]:
h = np.full((2,3),8)
print(h)


[[8 8 8]
 [8 8 8]]


In [16]:
i = np.random.rand(4,5)
print(i)


[[0.1756925  0.98018685 0.1704216  0.8732859  0.96272055]
 [0.6728375  0.28085361 0.80712017 0.9301172  0.18911016]
 [0.84798112 0.11583243 0.09692294 0.41101585 0.30550628]
 [0.68519463 0.46787348 0.65785975 0.76306696 0.39991066]]


In [17]:
j = np.random.rand(6,7) * 100
print(j)


[[49.13860727 46.71356059 57.14806923 30.00774254 28.53586812 40.79287444
  87.04050183]
 [59.24735344 90.62699157 42.98302984 17.6992372  84.40846051 39.77274094
  15.97217655]
 [54.72079259  6.29692136 74.83044448 15.79229272  8.20230439  2.98565143
  22.68156183]
 [59.58613534 80.35344659 87.80389687 66.08913196 94.78571181 38.23191999
  80.74792338]
 [90.40931743 14.71844039 58.73867883 14.97561372 40.76752051 44.44732036
  88.1601346 ]
 [82.73153882 89.09194092 11.29688296 73.70177463 68.92527222 78.09072976
  13.70574215]]


In [18]:
k = np.random.randint(5, size=(2,3))
print(k)


[[2 4 3]
 [1 3 0]]


#INSPECTING PROPERTIES

In [19]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr.size


9

In [21]:
arr.shape


(3, 3)

In [22]:
arr.dtype


dtype('int64')

In [23]:
arr.astype(float)


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [24]:
arr.tolist()


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
np.info(np.eye)


 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If 

#COPYING/SORTING/RESHAPING

In [26]:
np.copy(arr)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.view(float)


array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [28]:
arr.sort()


In [29]:
arr.sort(axis=0)


In [30]:
two_d_arr = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [31]:
two_d_arr.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
arr.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [35]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
arr.resize((5,6), refcheck=False)


In [37]:
print(arr)

[[1 2 3 4 5 6]
 [7 8 9 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#ADDING/REMOVING ELEMENTS

In [38]:
print(a)

[1 2 3]


In [39]:
print(arr)

[[1 2 3 4 5 6]
 [7 8 9 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [40]:
np.append(arr, a)


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3])

In [41]:
np.insert(arr, 2, a)


array([1, 2, 1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.delete(arr, 3, axis=0)


array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [43]:
np.delete(arr, 4, axis=1)


array([[1, 2, 3, 4, 6],
       [7, 8, 9, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#COMBINING/SPLITTING

In [44]:
arr1=np.eye(5)
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
arr2=np.eye(5)
print(arr2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
np.concatenate((arr1, arr2), axis=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.concatenate((arr1, arr2), axis=1)


array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [48]:
np.split(arr1, 5)


[array([[1., 0., 0., 0., 0.]]),
 array([[0., 1., 0., 0., 0.]]),
 array([[0., 0., 1., 0., 0.]]),
 array([[0., 0., 0., 1., 0.]]),
 array([[0., 0., 0., 0., 1.]])]

In [49]:
arr3 = np.eye(4)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
result = np.hsplit(arr, 2)

In [51]:
for i, part in enumerate(result, 1):
    print(f"Part {i}:\n", part)

Part 1:
 [[1 2 3]
 [7 8 9]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Part 2:
 [[4 5 6]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


#INDEXING/SLICING/SUBSETTING

In [52]:
new_arr2d = np.array([[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90]])


In [53]:
new_arr2d[2, 1]  # Returns the element at row 2, column 1 (0-based index)


np.int64(80)

In [54]:
new_arr2d[1, 2] = 100  # Assigns 100 to element at row 1, column 2


In [55]:
new_arr2d[0:2, 1]  # Returns elements from rows 0 to 1 of column 1


array([20, 50])

In [56]:
new_arr2d[:, 1]  # Returns all elements of column 1


array([20, 50, 80])

In [57]:
new_arr = np.array([10, 20, 30, 40, 50, 60, 70])


In [58]:
new_arr[5]


np.int64(60)

In [59]:
new_arr[1] = 4  # Assigns array element at index 1 the value 4


In [60]:
new_arr[0:3]  # Returns the elements at indices 0,1,2


array([10,  4, 30])

In [61]:
new_arr[:2]  # Returns the elements at indices 0,1


array([10,  4])

In [62]:
new_arr < 50  # Returns a boolean array for elements less than 50


array([ True,  True,  True,  True, False, False, False])

In [63]:
new_arr[new_arr < 50]  # Returns array elements smaller than 50


array([10,  4, 30, 40])

#SCALAR MATH

In [64]:
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])

In [65]:
np.add(arr2d, 1)


array([[ 6, 11, 16],
       [21, 26, 31],
       [36, 41, 46]])

In [66]:
np.subtract(arr2d, 2)


array([[ 3,  8, 13],
       [18, 23, 28],
       [33, 38, 43]])

In [67]:
np.multiply(arr2d, 3)


array([[ 15,  30,  45],
       [ 60,  75,  90],
       [105, 120, 135]])

In [68]:
np.divide(arr2d, 4)


array([[ 1.25,  2.5 ,  3.75],
       [ 5.  ,  6.25,  7.5 ],
       [ 8.75, 10.  , 11.25]])

In [69]:
np.power(arr2d, 5)


array([[     3125,    100000,    759375],
       [  3200000,   9765625,  24300000],
       [ 52521875, 102400000, 184528125]])

#VECTOR MATH

In [70]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print(arr1,arr2)

[1 2 3 4 5] [5 4 3 2 1]


In [71]:
np.add(arr1, arr2)

array([6, 6, 6, 6, 6])

In [72]:
np.subtract(arr1, arr2)

array([-4, -2,  0,  2,  4])

In [73]:
np.multiply(arr1, arr2) 

array([5, 8, 9, 8, 5])

In [74]:
np.divide(arr1, arr2)

array([0.2, 0.5, 1. , 2. , 5. ])

In [75]:
np.power(arr1, arr2)

array([ 1, 16, 27, 16,  5])

In [76]:
np.array_equal(arr1, arr2)

False

In [77]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [78]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [79]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [80]:
np.ceil(arr1 / 2.5)

array([1., 1., 2., 2., 2.])

In [81]:
np.floor(arr1 / 2.5)

array([0., 0., 1., 1., 2.])

In [82]:
np.round(arr1 / 2.5) 

array([0., 1., 1., 2., 2.])

#STATISTICS

In [83]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [84]:
print(arr.sum())


21


In [85]:
print(arr.min()) 


1


In [86]:
print(arr.max(axis=0)) 


[4 5 6]


In [87]:
print(np.var(arr))


2.9166666666666665


In [88]:
print(np.std(arr, axis=1))


[0.81649658 0.81649658]


In [89]:
print(np.corrcoef(arr))  


[[1. 1.]
 [1. 1.]]
